linters:
  enable:
    - misspell
    - revive
    - gocritic
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/vladiant/test_golang_ci

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
