version: "2"

linters:
  enable:
    - misspell
    - revive
    - gocritic

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vladiant/test_golang_ci

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
